name: FB-Bot-Runner

on:
  push:
    branches: [ main ]
  workflow_dispatch: # এটি দিলে আপনি হাত দিয়েও রান করতে পারবেন

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install fca-project-orion fs-extra express

    - name: Run Bot
      run: node index.js



