name: FB-Bot-Runner

on:
  push:
    branches: [ main ]
  workflow_dispatch: # এটি খুবই জরুরি, যাতে আপনি বাটন টিপে বট স্টার্ট দিতে পারেন

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      # --no-package-lock দিলে ইনস্টল দ্রুত হবে
      run: npm install --no-package-lock

    - name: Start Bot
      env:
        PORT: 8080
      # সরাসরি index.js রান করছি যাতে ভুল না হয়
      run: node index.js
